In [1]:
import pandas as pd
import numpy as np
# import

In [7]:
df = pd.read_csv("/Users/khusboopatel/Desktop/SSW 565/Project/Code_Review_Project-1.csv")
df.head(5)

,url,subject,description,owner_id,owner_name,reviewer_id,reviewer_name
0,https://review.opendev.org/794283,Enable etcd with security setting.,Enable etcd with security setting. Add etcd cl...,24,Chuck Short,[28570],['zhipeng liu']
1,https://review.opendev.org/789403,Add new Debian security mirror suite pattern,Add new Debian security mirror suite pattern S...,5263,Jeremy Stanley,[],[]
2,https://review.opendev.org/741345,Fix rule replacement in security policy,Fix rule replacement in security policy Change...,24247,Anna Khmelnitsky,[],[]
3,https://review.opendev.org/637381,OvS: Add pod security context to pods,OvS: Add pod security context to pods This PS ...,23928,Pete Birley,[22348],['Zuul']
4,https://review.opendev.org/615355,Horizon: update east-west network security policy,Horizon: update east-west network security pol...,17119,Dmitrii Kabanov,"[20466, 20469, 22348, 22636]","['Tin Lam', 'Tin Lam', 'Zuul', 'Cliff Parsons']"

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3075 entries, 0 to 3074
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   url            3075 non-null   object
 1   subject        3075 non-null   object
 2   description    3075 non-null   object
 3   owner_id       3075 non-null   int64
 4   owner_name     3075 non-null   object
 5   reviewer_id    3075 non-null   object
 6   reviewer_name  3075 non-null   object
dtypes: int64(1), object(6)
memory usage: 168.3+ KB

In [16]:
df = pd.read_csv("/Users/khusboopatel/Desktop/SSW 565/Project/p1.csv")
df.head(10)

,Unnamed: 0,label_st1,count,label,top_ground_category,top_cat_count,perc_top_cat
0,0,-1,549,add_id_security_group,add_security_group_policy,1001,182
1,1,59,190,add_rule_security_group,add_security_group_policy,233,123
2,2,74,189,add_id_security_bug,add_security_policy,191,101
3,3,32,182,adds_context_security_container,add_context_security_container,217,119
4,4,81,100,add_test_security_group,add_unit_test,100,100
5,5,26,69,nsx|p_id_security_group,add_security_policy,95,138
6,6,88,68,add_id_security_group,add_security_group_policy,1001,1472
7,7,58,64,add_group_security,add_security_group_policy,240,375
8,8,80,62,add_id_security_group,add_security_group_policy,1001,1615
9,9,79,60,add_group_security,add_security_group_policy,240,400

In [19]:
df = pd.read_csv("/Users/khusboopatel/Desktop/SSW 565/Project/df_comparison.csv")
df.head()

,Unnamed: 0,Model,ARI,NMI,loss,label_count,n_neighbors,n_components,min_cluster_size,random_state
0,1,st1,0.171,0.568,0.180813,90,3,6,8,42
1,2,st2,0.052,0.301,0.209106,89,12,11,6,42
2,3,st3,0.145,0.179,0.179919,4,8,7,15,42
3,0,use,0.112,0.149,0.164309,4,9,8,13,42

In [15]:
df = pd.read_csv("/Users/khusboopatel/Desktop/SSW 565/Project/compare_stats.csv")
df.head(5)

,Model,ARI,NMI,loss,label_count,n_neighbors,n_components,min_cluster_size,random_state
0,st1,0.171,0.568,0.180813,90,3,6,8,42
1,st2,0.052,0.301,0.209106,89,12,11,6,42
2,st3,0.145,0.179,0.179919,4,8,7,15,42
3,use,0.112,0.149,0.164309,4,9,8,13,42

In [26]:
df = pd.read_csv("/Users/khusboopatel/Desktop/SSW 565/Project/models_labels_results.csv")
df.head(15)
# print(df)

,Unnamed: 0,text,category,label_use,label_st1,label_st2,label_st3
0,0,Enable etcd with security setting Add etcd cli...,add_context_security_etcd,2,29,-1,1
1,1,Add new Debian security mirror suite pattern S...,add_security_mirror_repository,2,55,34,2
2,2,Fix rule replacement in security policy Change...,add_security_policy,2,71,41,2
3,3,OvS: Add pod security context to pods This PS ...,add_context_security_container,1,32,11,1
4,4,Horizon: update east-west network security pol...,add_security_group_policy,2,59,29,2
5,5,Implement helm-toolkit snippet to Keystone pod...,add_context_security_container,1,32,11,1
6,6,Add missing security context to Mini-mirror te...,add_context_security_container,1,3,11,1
7,7,Enable setting default rules for default secur...,add_security_group_policy,2,58,43,2
8,8,Testingrst misses a step for adding security r...,add_unit_test,2,81,-1,2
9,9,Test security groups Install ovs kernel module...,add_security_group_policy,2,35,-1,2
10,10,Add OSSN-0040 security groups don't work with ...,add_security_group_policy,2,35,68,2
11,11,Add security groups dscp spec This adds the sp...,add_security_group_policy,2,64,-1,2
12,12,Open vSwitch-based Security Groups: OVS Firewa...,add_security_group_policy,2,35,68,2
13,13,Add security groups for nova As current implem...,add_security_group_policy,2,58,72,2
14,14,Add security to libvirtd Allow libvirt to be a...,add_unit_test,2,13,8,-1